### ISSUE TITLE
awkwardneß

### ISSUE THREAD

**Issue by AlcedoAttis** [nodatapoints/nodatabot#4]
I think it is a big issue if only those who contribute to the project open issues.
It comes of a bit awkward.

possible fix: discuss issues privately
@AlcedoAttis @nodatapoints @CVTTSD2SI

**Comment by CVTTSD2SI** [comment]
I honestly believe the most awkward thing is writing awkwardness with a single s in issue titles. Lass doch Kamal seinen Spaß.

**Comment by AlcedoAttis** [comment]
Englisch is not my Motherspeak @CVTTSD2SI
